name: Publish 🚀🎯

on:
  workflow_dispatch:
  push:
    branches:
      - Deployment

env: 
  AZURE_WEBAPP_NAME: dg-event-scheduler-api
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./event-scheduler.api.sln

      - name: Build
        run: dotnet build ./event-scheduler.api.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./event-scheduler.api.sln --configuration Release --no-build --output '${{env.AZURE_WEBAPP_PACKAGE_PATH}}'

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
          package:  "${{env.AZURE_WEBAPP_PACKAGE_PATH}}"
     
